name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i && git diff --exit-code

      - name: Tests
        run: make DEBUG=1 test && time seq 100 | xargs -I{} -n 1 -P 1 ./test

      - name: Build application
        run: make DEBUG=1