name: ATests

on: 
  push:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Tests
        run: make test

      - name: ctest
        run: ./bin/test  
